### ISSUE TITLE
Work together?

### ISSUE THREAD

**Issue by rrag** [Svjard/ng2-stockcharts#7]
Hey @Svjard 
It is great to see an adaptation of react-stockcharts in ng2.

I see you have some type definitions created using typescript, I have also been thinking of switching to typescript, may be we can join forces and share these bindings. Also there are some things I am experimenting with the development branch so it might be worth your time to not review certain parts which are work in progress as it could change the soon.

A lot of code is not react specific, primarily the algorithms for indicators and the scales. There is opportunity to share those too. Better communication between us can make both of these strong.

**Comment by Svjard** [comment]
Hey @rrag,

Absolutely! I love the work you've done on react-stockcharts, had to have an ng2 implementation due to constraints outside my control though. 

I can certainly help out if you are looking to go to Typescript. Are you looking to just provide typings or convert the entire code base? I figure some of the `next` branch was experimental, would be helpful to avoid porting some of that. I am trying to spend a lot of time on the tests as well as I go though.

Proposal for best way to work together?

**Comment by rrag** [comment]
convert entire codebase to typescript. I am now focussed on getting 0.5 out, after that, 0.6 will likely be some leftovers which I had planned for 0.5 but could not make it.

0.7 is going to be a major refactor breaking up to use multiple modules, use d3 4.0. I was hoping to use this as the time to convert to typescript too. This is where I was thinking we can even share some modules and common code

Ah Tests :) I am guilty of not writing them. may be 0.7 is the time or may be never

About working together, What about a chat on gitter or email each other from time to time about our plans.

For now I am working on refactoring the interactive indicators, so they will be completely broken in the next branch now.

Also currently I have no plans to support non cartesian charts like pie or donut, I see you wish to support them, which is cool but I believe doing a canvas version for those types is a waste of time. Canvas shines only when there are a many elements and you need a redraw them fast, like with pan

**Comment by Svjard** [comment]
Gotcha. Email works fine for me. I am also interested in getting to d3 4.0 but I am waiting for the typings to catch up so don't forsee that switch for another month maybe two.

The pie/donut wasn't really because I wanted those chart types as standalone, more as a customization feature of Bubble charts (bubbles being pie/donut markers instead). It is not a high priority at all for me, just going to focus on the core charts you already have initially.

BTW if you tag any of your issues with [Help Wanted] I'll try to help contribute as I can, React is what I generally work with outside of work.

**Comment by rrag** [comment]
Great, thank you
